disabled_rules: 
  - trailing_whitespace
  - identifier_name
  - force_cast
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - block_based_kvo

line_length:
  warning: 180
